language: python
install: pip install coverage codecov
matrix:
  include:
  - name: flake8
    install: pip install flake8
    python: "3.6"
    script:
    - flake8 . --count --show-source --statistics
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
script:
  - cd code
  - coverage run test_png.py
  - codecov
